# Generated by Django 4.1.1 on 2022-11-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_appUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('devicename', models.CharField(db_column='DeviceName', max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Device',
                'db_table': 'Device',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('targetnum', models.SmallAutoField(db_column='TargetNum', primary_key=True, serialize=False)),
                ('targetname', models.CharField(blank=True, db_column='TargetName', max_length=32, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=1, null=True)),
                ('image', models.TextField(blank=True, db_column='Image', null=True)),
                ('birthdate', models.DateTimeField(blank=True, db_column='BirthDate', null=True)),
                ('targetage', models.IntegerField(blank=True, db_column='TargetAge', null=True)),
                ('missingornot', models.IntegerField(blank=True, db_column='MissingOrNot', null=True)),
                ('urgentnum', models.CharField(blank=True, db_column='UrgentNum', max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Target',
                'verbose_name_plural': 'Target',
                'db_table': 'Target',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
    ]
