# Generated by Django 4.1.1 on 2022-11-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_appUser', '0002_device_target_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
