# Generated by Django 4.1.1 on 2022-11-27 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend_appUser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingInfo',
            fields=[
                ('infonum', models.SmallAutoField(db_column='InfoNum', primary_key=True, serialize=False)),
                ('disappearancetime', models.DateTimeField(db_column='DisappearanceTime')),
                ('disappearancearea', models.TextField(blank=True, db_column='DisappearanceArea', null=True)),
            ],
            options={
                'verbose_name': 'Missing_Info',
                'verbose_name_plural': 'Missing_Info',
                'db_table': 'Missing_Info',
            },
        ),
        migrations.CreateModel(
            name='MissingProtector',
            fields=[
                ('protectornum', models.SmallAutoField(db_column='ProtectorNum', primary_key=True, serialize=False)),
                ('protectorname', models.CharField(blank=True, db_column='ProtectorName', max_length=32, null=True)),
                ('protectorphonenum', models.CharField(blank=True, db_column='ProtectorPhoneNum', max_length=32, null=True)),
            ],
            options={
                'verbose_name': 'Missing_Protector',
                'verbose_name_plural': 'Missing_Protector',
                'db_table': 'Missing_Protector',
            },
        ),
        migrations.CreateModel(
            name='MissingAnnouncement',
            fields=[
                ('announcementnum', models.SmallAutoField(db_column='AnnouncementNum', primary_key=True, serialize=False)),
                ('missingname', models.CharField(blank=True, db_column='MissingName', max_length=32, null=True)),
                ('missingimage', models.TextField(blank=True, db_column='MissingImage', null=True)),
                ('enroll_time', models.DateTimeField(db_column='Enroll_Time')),
                ('infonum', models.ForeignKey(db_column='InfoNum', on_delete=django.db.models.deletion.DO_NOTHING, to='backend_appService.missinginfo')),
                ('protectornum', models.ForeignKey(db_column='ProtectorNum', on_delete=django.db.models.deletion.DO_NOTHING, to='backend_appService.missingprotector')),
            ],
            options={
                'verbose_name': 'Missing_Announcement',
                'verbose_name_plural': 'Missing_Announcement',
                'db_table': 'Missing_Announcement',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('targetnum', models.OneToOneField(db_column='TargetNum', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backend_appUser.target')),
                ('usernum', models.ForeignKey(db_column='UserNum', on_delete=django.db.models.deletion.DO_NOTHING, to='backend_appUser.user')),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Search',
                'db_table': 'Search',
                'unique_together': {('targetnum', 'usernum')},
            },
        ),
        migrations.CreateModel(
            name='Pastpath',
            fields=[
                ('devicename', models.OneToOneField(db_column='DeviceName', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backend_appUser.device')),
                ('signaledtime', models.DateTimeField(db_column='SignaledTime')),
                ('latitude', models.FloatField(blank=True, db_column='Latitude', null=True)),
                ('longitude', models.FloatField(blank=True, db_column='Longitude', null=True)),
                ('targetnum', models.ForeignKey(db_column='TargetNum', on_delete=django.db.models.deletion.DO_NOTHING, to='backend_appUser.target')),
                ('usernum', models.ForeignKey(db_column='UserNum', on_delete=django.db.models.deletion.DO_NOTHING, to='backend_appUser.user')),
            ],
            options={
                'verbose_name': 'PastPath',
                'verbose_name_plural': 'PastPath',
                'db_table': 'PastPath',
                'unique_together': {('devicename', 'targetnum', 'usernum', 'signaledtime')},
            },
        ),
    ]
