# Generated by Django 4.1.1 on 2022-11-20 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_appService', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
