# Generated by Django 4.1.1 on 2022-11-26 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_appUser', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
